import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <link rel="icon" href="/favicon.png" sizes="any" />
        <link href="https://fonts.googleapis.com/css2?family=Praise&family=Salsa&display=swap" rel="stylesheet"/>
    </head>
    <body>
      <div className="relative w-screen h-screen bg-[#790b73cd] cursor-custom">
        <div className="absolute top-1/2 left-1/2 rotate-90 sm:rotate-0 transform -translate-x-1/2 -translate-y-1/2 flex items-center justify-center w-[100vh] h-[100vw] sm:w-screen sm:h-screen">
          {children}
        </div>
      </div>
    </body>
  </html>
  );
}
